export default {
    deleteItem: '[data-context="instance"][data-action="deleteItem"]',
    deleteClass: '[data-context="class"][data-action="deleteItemClass"]',
    moveClass: '[id="class-move-to"][data-context="class"][data-action="moveTo"]',
    moveConfirmSelector: 'button[data-control="ok"]',
    newClass: '[data-context="resource"][data-action="subClass"]',
    addItem: '[data-context="resource"][data-action="instanciate"]',
    importItem: '[data-context="resource"][data-action="loadClass"]',
    exportItem: '[data-context="resource"][data-action="load"]',
    itemForm: 'form[action="/taoItems/Items/editItem"]',
    itemClassForm: 'form[action="/taoItems/Items/editClassLabel"]',
    classOptions: '[action="/taoItems/Items/editItemClass"]',
    editClass: '#item-class-schema',
    classForm: 'form[data-action= "/taoItems/Items/editItemClass"]',
    propertyEdit: 'div[class="form-group property-block regular-property property-edit-container-open"]',
    deleteConfirm: '[data-control="delete"]',
    root: '[data-uri="http://www.tao.lu/Ontologies/TAOItem.rdf#Item"]',
    editClassLabelUrl: 'taoItems/Items/editClassLabel',
    editItemUrl: 'taoItems/Items/editItem',
    treeRenderUrl: 'taoItems/Items',
    addSubClassUrl: 'taoItems/Items/addSubClass',
    editClassUrl: 'taoItems/Items/editItemClass',
    deleteClassUrl: 'taoItems/Items/deleteClass',
    restResourceGetAll: 'tao/RestResource/getAll',
    resourceRelations: 'tao/ResourceRelations',
    importItemUrl: 'taoItems/ItemImport/index',
    exportItemUrl: 'taoItems/ItemExport/index'
};
