name: Continuous integration

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ develop ]

jobs:
  ci:
    runs-on: ${{ matrix.operating-system }}

    strategy:
      fail-fast: false
      matrix:
        operating-system: [ ubuntu-latest ]
        php-version: [ '7.4', '8.0', '8.1' ]
        include:
          - php-version: '7.4'
            coverage: true

    steps:
      - name: CI
        uses: oat-sa/tao-extension-ci-action@e70f8c1aadc1622d2a8620ddf2524c6f0ca613a0
        with:
          php: ${{ matrix.php-version }}
          coverage: ${{ matrix.coverage }}