name: PSR-12 check

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ develop, php8-migration ]

jobs:
  ci:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        operating-system: [ ubuntu-latest ]
        php-version: [ '7.4', '8.0', '8.1' ]
        include:
          - php-version: '7.4'
            coverage: true

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: "Cache dependencies installed with composer"
        uses: actions/cache@v1
        with:
          path: ~/.composer/cache
          key: php${{ matrix.php-version }}-composer-${{ hashFiles('**/composer.json') }}
          restore-keys: |
            php${{ matrix.php-version }}-composer-

      - name: Install Composer dependencies
        run: composer install --no-progress --dev

      - name: Run PHP Code Sniffer PSR-12 check
        run: vendor/bin/phpcs --standard=PSR12 -v actions config helpers includes migrations models/classes scripts test
