name: PSR-12 check

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ develop, php8-migration ]

jobs:
  ci:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 7.2

      - name: "Cache dependencies installed with composer"
        uses: actions/cache@v1
        with:
          path: ~/.composer/cache
          key: php${{ matrix.php-version }}-composer-${{ hashFiles('**/composer.json') }}
          restore-keys: |
            php${{ matrix.php-version }}-composer-

      - name: Install Composer dependencies
        run: composer install --no-progress --dev --no-plugins

      - id: files
        uses: jitterbit/get-changed-files@v1
        with:
          format: 'csv'
      - run: |
          FILELIST=$(mktemp /tmp/psr12-check.XXXXXX)
          mapfile -d ',' -t added_modified_files < <(printf '%s,' '${{ steps.files.outputs.added_modified }}')
          for FILE in "${added_modified_files[@]}"; do
              EXT="${FILE##*.}"
              echo "Changed file: " $FILE ", extension: " $EXT
              if [ "$EXT" == "php" ]; then
                echo "${FILE}" >> "${FILELIST}"
                echo "File added to the file list: " $FILE
              fi
          done
          if [ -s "${FILELIST}" ]; then
              vendor/bin/phpcs --standard=PSR12 --exclude=PSR1.Classes.ClassDeclaration -v --file-list="${FILELIST}"
              RETVAL=$?
              echo "The following files were tested for PSR-12 errors:"; echo 
              cat -n "$FILELIST"
          else
              echo "There are no changes in PHP files (no PSR-12 test performed)"
          fi
          rm "$FILELIST"
          exit $RETVAL
